name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - name: Install test dependencies
      run: |
        py -3.10 -m pip install --upgrade pip
        py -3.10 -m pip install -r dev-requirements.txt
    - name: Test
      run: |
        pytest tests
